### ISSUE TITLE
Basic query planner couldn't query view table

### ISSUE THREAD

**Issue by cutsea110** [cutsea110/simpledb#51]
``` sql
SQL> select sname, grade, prof from student, enroll, einstein where sid=student_id and sect_id=section_id;
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/record/schema.rs:54:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cutsea110** [comment]
This is not view bug. This is a known bug about unknown field.

* view of **einstein**

```sql
SQL> :v einstein
view name: einstein
view def:
 > select sect_id from section where prof='einstein'
```

* success to query with view **einstein**

```sql
SQL> select sid, sname, grade from student, einstein, enroll where sid=student_id and sect_id=section_id;
sid     sname       grade
---------------------------
      1 joe         C
      2 amy         B+
transaction 2 committed
Rows 2 (0.008s)
```

* Fail to this query as bellow, because this query access prof field which doesn't exists in this query.

```
SQL> select sid, sname, grade, prof from student, einstein, enroll where sid=student_id and sect_id=section_id;
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/record/schema.rs:54:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:755:21
   4: simpledb::record::schema::Schema::field_type
             at ./src/record/schema.rs:54:9
   5: simpledb::record::schema::Schema::add
             at ./src/record/schema.rs:38:24
   6: simpledb::plan::projectplan::ProjectPlan::new
             at ./src/plan/projectplan.rs:75:13
   7: <simpledb::plan::basicqueryplanner::BasicQueryPlanner as simpledb::plan::queryplanner::QueryPlanner>::create_plan
             at ./src/plan/basicqueryplanner.rs:61:21
   8: simpledb::plan::planner::Planner::create_query_plan
             at ./src/plan/planner.rs:54:9
   9: <simpledb::rdbc::embedded::statement::EmbeddedStatement as simpledb::rdbc::statementadapter::StatementAdapter>::execute_query
             at ./src/rdbc/embedded/statement.rs:46:15
  10: esql::execquery::exec_query
             at ./app/embedded/execquery.rs:80:11
  11: esql::exec
             at ./app/embedded/main.rs:118:13
  12: esql::main
             at ./app/embedded/main.rs:159:9
  13: core::ops::function::FnOnce::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
